### ISSUE TITLE
Error: 'CGSizeValue' is unavailable: not available on watchOS

### ISSUE THREAD

**Issue by joshuajohncohen** [Darock-Studio/Watch-Browser#4]
Error: /Users/NAME/Library/Developer/Xcode/DerivedData/WatchBrowser-etncosmxkjfanybfnlocmboxwwsv/SourcePackages/checkouts/SDWebImage/SDWebImage/Core/UIImage+Metadata.m:209:44 'CGSizeValue' is unavailable: not available on watchOS

**Comment by WindowsMEMZ** [comment]
It's Apple's bug. I've filed a feedback and posted on [Apple Developer Forums](https://developer.apple.com/forums/thread/759522). For a workaround, you can use Xcode 16.0 or older version to build it.

**Comment by WindowsMEMZ** [comment]
Apple has fixed this issue in Xcode 16.0 Beta 4
